import type {Metadata} from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Pimp my room",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="dark max-h-screen w-full bg-background px-4 font-sans antialiased">
        <header className="text-center text-2xl font-bold leading-[4rem]">
          <h1 className="my-6 text-5xl font-bold">Pimp my room!</h1>
        </header>
        <main className="container mx-auto w-full">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} replicate-project
        </footer>
      </body>
    </html>
  );
}
